# 1. What is Data?
Data means raw facts, figures, observations, or information collected for a particular purpose.
Data can be numerical or categorical.

# 2. What is Statistics?
Statistics is the science of collecting, organizing, processing, analyzing, interpreting, and presenting data to make informed decisions.
Statistics converts raw data into meaningful information that can be used for decision-making.
    Step 1: Data Collection
            Collect raw data from different sources.
    Step 2: Organization
            After collecting raw data, we organize it into a structured format.
            like : Table, Excel sheets, Dataframes, Databases
    Step 3: Data Processing
            We clean and prepare the data for analysis.
            like : Handling missing values, Removing duplicates, Correcting errors.
    Step 4: Data Analysis
            We analyze the processed data to find patterns, relationships, and useful information.
            like : mean, median, mode, aggregations, correlation, trends
    Step 5: Data Interpretation
            We explain what the analyzed results actually mean.
    Step 6: Data Presentation
            We present the results in an easy-to-understand format.
            like: charts, graphs, tables, dashboards, kpis, powepoint presentations.
    Step 7: Decision Making
            The information obtained from the analysis is used to make informed decisions.
    Step 8: Monitoring & Governance
            After making a decision, we continue to monitor the data and maintain its quality.

# 3. Types of Statistics
There are three important areas you should remember:
    A. Descriptive Statistics
          Descriptive statistics are used to summarize and describe data. 
          Mean - Average 
          Median - Middle value
          Mode - Most frequently occuring value 
    B. Measures of Dispersion
          Dispersion tells us how spread out or scattered the data is.  
          Range
          Variance
          Standard Deviation
          IQR (Interquartile Range) 
    C. Inferential Statistics
          Inferential statistics are used to make conclusions or predictions about a population using sample data.
          Hypothesis Testing
          t-test
          z-test
          ANOVA
          Chi-square test

# 4. Types of Data
                    DATA
                     |
          -----------|-----------
         |                     |
     Numerical              Categorical
         |                     |
    -----|-------         -----|------
    |           |         |          | 
 Discrete   Continuous  Nominal    Ordinal

# 5. Numerical Data
Numerical data represents numbers or measurable quantities.
It has Two types: 
      A. Discrete Data
            Discrete data consists of countable whole numbers (integers).
            You generally get discrete data by counting. 
      B. Continuous Data
            Continuous data can take decimal values and is generally obtained through measurement.

# 6. Categorical Data
Categorical data represents groups, labels, or categories rather than numerical measurements.
It has two main types:
       A. Nominal Data
             Nominal data consists of categories that do not have any natural order or ranking.
       B. Ordinal Data
             Ordinal data consists of categories that have a meaningful order or ranking.
             Like: Low, Medium, High
                   Poor, Average, Good

# 7. Statistics and Machine Learning
Statistics is very important in Machine Learning (ML).
ML uses statistical concepts to:
     Understand data
     Find patterns
     Measure relationships
     Make predictions
     Evaluate models
     Handle uncertainty

Important concepts:
    Probability -> Machine Learning Algorithms
         Probability helps ML models deal with uncertainty and likelihood.
    Vectors -> NLP & Deep Learning
         Vectors are used to represent data numerically.
For example, in NLP, words can be represented as numerical vectors called embeddings.

# 8.Population vs Sample AND Random Sampling
Population
    Population = The entire group or universe that we are interested in studying.
    Example:
    Suppose we want to study the salaries of all employees in a company.
    If the company has 10,000 employees:
    Population: All 10,000 employees.

Sample
    Sample = A smaller subset selected from the population for analysis.
    Instead of asking all 10,000 employees, we may select 500 employees.
    It is a part of the population 

Random Sampling
    A sample should ideally be selected in a way that represents the population.
    Example:
     If a college has: 60% Female and 40% Male 
     and we randomly select a sample of 100 students, the sample should ideally have a reasonably similar representation. 
     A good sample should be representative of the population.
     Random sampling helps reduce selection bias and gives each population member a fair chance of being selected.

In [1]:
import numpy as np
np.random.seed(123)
population = np.random.randint(0,100,size=1000)
print(population)

[66 92 98 17 83 57 86 97 96 47 73 32 46 96 25 83 78 36 96 80 68 49 55 67
  2 84 39 66 84 47 61 48  7 99 92 52 97 85 94 27 34 97 76 40  3 69 64 75
 34 58 10 22 77 18 15 27 30 52 70 26 80  6 14 75 54 71  1 43 58 55 25 50
 84 56 49 12 18 81  1 51 44 48 56 91 49 86  3 67 11 21 89 98  3 11  3 94
  6  9 87 14 83 70 12 54 27 38 17 61 74 99 99 65 47 16  5 86 46 15 59 40
 25 45 49  0 35 29  1 83 68 30  7 93 60 65 76 67 44 51  7 88 70 13 28 63
 84 36 96 40 88 63 58 77  8 78  6 65 94 70 40 74 76 76 25  7 13 44  1 41
 78 56 87 63 97  3 17 88 87 69 97 50  2 18 46 45 57 35 18 91 46 54 73 81
 62 67 11 26 92 75 10  3 45 58 59 23 25 27 57  3 99 78 85 59 48 56 87 87
  4 69 56 60  9 66 33 69  9 79 28 66 10  3 48  3 23 91 55 34 37 49 87 85
 25 17 58 66 45 10  8 96 25 99 67 65  7 70 99 97 39 82 92 38  5  9 40 68
 87 21 89 50 36 44 92 99 83 81 61 14 78 23 62 28 80 24 15 49 80 84 90  4
 21 32 39  1 98 82 90 35 58 38  1 52 17 45 22 53 89 74  0 35 83 94 71 39
 87 83 78 29 19 37  1  5 81 35 77 25 97 93 70 58 29 81 21 16 30 55 80 30
 12 90 83 16 92 38 98  7 37 14  0 96  2 37 47 62 61 14 61 81 37 94 19 58
  6 90 71 77 78 70 96 51 97  3  0 77 94 37 52 83  2 98 96 14  2 91 90 32
 82 55 32 30  3 95 91 79 91 78 21 30 59 84 31 70 96  7 77 61 88 95 27 65
 16 90  1  7 37 19 63 20 89 30 83 69 14 56  0 89 28 65 21 60 28  8 40 20
 54 95 95 39 25 47 76  2 95 32 96 41 76 42 69  3 63 69 50 66 90 83 17 19
 29 73 51 22 46  2 49  8 18 35 39 26 91 71 71 81 20 12 26 61 39 52 79 39
  8 26 80  2 55 52  3 39 51 55 64 77 71 70 29 24 38 79 74 24 32 62 53 50
 84 51 51 73 55 72  0 97 30 20 23 18 60 59 84 24 19 25  6 66 55 71 93 10
 71 16 71 46 43 63 29 42 15  3 84 49 33 34 63 12 26 71 40 41 28 15 52 45
 68 36 59 73 14 20 33 85 85  8 25 76 17  0 22 32 46 94 20 86 79 60 26 62
 51 63 13 46  6 75 27  2 21 84 62 28 19 66 90 84 32 93 47 40  8 47 86 53
 22 64 20 31 25 32 59  8 80 69 45  6  6 68 32  9 80 27 46 45 21 20 55 31
 31 35 30 69 53 20 34 77 22 41 23 93 73 68 41 29 70  5 71 51 89 81 99 25
 99 40 67 53 59 76 54 23 94 85 39 81 63 33 86 38  0 19 24  5 93 83 72 81
  2 35 69 37 64 82 37 27 46 72 46  9 87 89 71  4 12 85 33 24 22 84  2  7
 45 61 38 50 21 44 74 22 48 79 50 27 98 28 58 69 77 92 27 73 46  3 87  1
 63 28 88 94 46 14 37 96 48 71 39 15 33  5 86 52 20 98 28 98  1 96 25 43
 95 17 97 29 22 47 54 83 22 39 63 71 13 86 77  1  3 87 99  8 15 95 31 26
 14 67 99 24 14 11 70 99 23 69 40 59 30 20 59 74 79 77 88 13 81 13 23 71
 24 97 27 87 17 56 97 41 66 11 35 68 82 75 90 16 42 91 39 21 63  9  5 16
 75 62 69 85 49 79 67 24 32  0 78 16 42 57 18 53 82 83  0 86 15 23 83 78
 63 57 23 57 63 40 32 95 57 55 94 14 64 11 34 36 29 89 10 59 31  1  9 45
 21 72 54 58 29 52 88 20 81 19 79 38 34 28 55 93 54 52 47 66 54 31 57 77
 89 68 27 71 96 99 59 12 83 17 50 49 83 42 96 84 45 23 91  4 29 42 52 23
 13 99 35 25 12 20 89 97 39 77 84 42 58 48 46 18 11 35 93 32 86 61 40 76
 91 91 18 30 49 41 16 91 67  5 59 18 57 86 39 44 41 69 23 21 52 84 77 23
 24 16 34 80 55 27 65 33 64  2 58 55 21 41  3 78 99 11 36 40 57 62 70 94
  4 90 88 16 27 26 52 25 48 92 59 26 80 37 79  8]

In [2]:
np.random.seed(20)
sample = np.random.choice(population,size=100)
print(sample)

[81 26 99 69 58 56 78 88 57 23  2 25 48 59 68 71 26 27  8 40 79 95 25 25
 73 84 27 52 99 52 97 59 86 15 76 55 23  3 49 27 23 57 41 14 32 79 55 21
 40 70 57 61 38 72 41  7  3 40 84 88 51 88 50 33 28 59 19  8 84 22 32 24
 35  1 32 49 76  9 18 35 27 22 29 54 60 49 57 87 40 84 78 94  1 77  7 55
 30 14 30 81]

In [3]:
import seaborn as sns
df = sns.load_dataset('titanic')
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [4]:
df.sample(10,random_state=42)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
709,1,3,male,NaN,1,1,15.2458,C,Third,man,True,NaN,Cherbourg,yes,False
439,0,2,male,31.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
840,0,3,male,20.0,0,0,7.9250,S,Third,man,True,NaN,Southampton,no,True
720,1,2,female,6.0,0,1,33.0000,S,Second,child,False,NaN,Southampton,yes,False
39,1,3,female,14.0,1,0,11.2417,C,Third,child,False,NaN,Cherbourg,yes,False
290,1,1,female,26.0,0,0,78.8500,S,First,woman,False,NaN,Southampton,yes,True
300,1,3,female,NaN,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True
333,0,3,male,16.0,2,0,18.0000,S,Third,man,True,NaN,Southampton,no,False
208,1,3,female,16.0,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True
136,1,1,female,19.0,0,2,26.2833,S,First,woman,False,D,Southampton,yes,False